advanced_search:
    field_definition_adapters:
        default: 'bundle.advanced_search.filter.default'
        calculatedValue: 'bundle.advanced_search.filter.calculatedValue'
        checkbox: 'bundle.advanced_search.filter.checkbox'
        country: 'bundle.advanced_search.filter.country'
        countrymultiselect: 'bundle.advanced_search.filter.countrymultiselect'
        date: 'bundle.advanced_search.filter.date'
        datetime: 'bundle.advanced_search.filter.datetime'
        input: 'bundle.advanced_search.filter.input'
        language: 'bundle.advanced_search.filter.language'
        languagemultiselect: 'bundle.advanced_search.filter.languagemultiselect'
        localizedfields: 'bundle.advanced_search.filter.localizedfields'
        multiselect: 'bundle.advanced_search.filter.multiselect'
        numeric: 'bundle.advanced_search.filter.numeric'
        quantityValue: 'bundle.advanced_search.filter.quantityValue'
        select: 'bundle.advanced_search.filter.select'
        time: 'bundle.advanced_search.filter.time'
        user: 'bundle.advanced_search.filter.user'
